/**
 * Restyles Clerk's `<SignIn />` / `<SignUp />` to match the Auth-page design handoff:
 * no card chrome (the widget sits directly on the split-screen page), pill-shaped
 * buttons, 12px inputs. Values reference the CSS custom properties in `globals.css`
 * — never raw hex.
 */
export const clerkAppearance = {
  variables: {
    colorPrimary: "var(--accent-primary)",
    colorPrimaryForeground: "#ffffff",
    colorBackground: "var(--bg-surface)",
    colorInput: "var(--bg-surface)",
    colorInputForeground: "var(--text-primary)",
    colorForeground: "var(--text-primary)",
    colorMutedForeground: "var(--text-secondary)",
    colorMuted: "var(--bg-subtle)",
    colorBorder: "var(--border-default)",
    colorRing: "var(--accent-primary)",
    colorDanger: "var(--state-error)",
    colorSuccess: "var(--state-success)",
    colorWarning: "var(--state-warning)",
    colorNeutral: "var(--text-muted)",
    colorShimmer: "var(--bg-subtle)",
    colorModalBackdrop: "rgba(11, 31, 38, .5)",
    borderRadius: "0.75rem",
    fontFamily: "var(--font-jakarta-sans)",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full shadow-none bg-transparent",
    card: "w-full border-none bg-transparent p-0 shadow-none",
    header: "gap-1.5 mb-1",
    headerTitle: "text-3xl font-extrabold leading-[1.1] tracking-tight text-copy-primary sm:text-4xl",
    headerSubtitle: "text-[15.5px] leading-relaxed text-copy-secondary",
    socialButtons: "gap-2",
    socialButtonsBlockButton:
      "rounded-full border-[1.5px] border-surface-border bg-surface px-4 py-[13px] transition-colors hover:border-subtle-border hover:bg-subtle active:scale-[.985]",
    socialButtonsBlockButtonText: "text-[15px] font-bold text-copy-primary",
    dividerRow: "gap-3.5 my-5",
    dividerLine: "bg-surface-border",
    dividerText: "text-xs font-semibold text-copy-muted",
    formFieldLabel: "text-[13.5px] font-bold text-copy-primary",
    formFieldLabelRow: "mb-[7px]",
    formFieldInput:
      "rounded-xl border-[1.5px] border-surface-border bg-surface px-[15px] py-[13px] text-[15px] text-copy-primary placeholder:text-copy-faint focus:border-brand focus:shadow-[0_0_0_3px_var(--accent-primary-dim)] focus:ring-0",
    formFieldInputShowPasswordButton: "rounded-lg text-copy-muted hover:bg-subtle hover:text-copy-primary",
    formFieldAction: "text-[13px] font-bold text-brand hover:text-brand-hover",
    formFieldHintText: "text-copy-muted",
    formFieldErrorText: "text-error",
    formFieldSuccessText: "text-success",
    formFieldWarningText: "text-warning",
    formFieldRow: "gap-4",
    formButtonPrimary:
      "mt-1 w-full rounded-full bg-brand px-4 py-[14px] text-[15.5px] font-bold normal-case text-white shadow-[0_4px_16px_rgba(3,89,127,.28)] hover:bg-brand-hover active:scale-[.985]",
    formButtonReset: "rounded-full font-bold text-brand hover:text-brand-hover hover:bg-transparent",
    footer: "hidden",
    identityPreview: "rounded-xl border-surface-border bg-subtle",
    identityPreviewText: "text-copy-primary",
    identityPreviewEditButton: "text-brand hover:text-brand-hover",
    otpCodeFieldInputs: "gap-2",
    otpCodeFieldInput:
      "aspect-square rounded-xl border-[1.5px] border-surface-border bg-surface text-[22px] font-bold text-copy-primary focus:border-brand focus:shadow-[0_0_0_3px_var(--accent-primary-dim)]",
    alertText: "text-sm text-error",
    badge: "rounded-full bg-accent-dim text-brand",
    button: "shadow-none",

    /* --- UserProfile (edit profile modal) --- */
    modalBackdrop: "backdrop-blur-sm",
    modalContent: "rounded-3xl bg-surface",
    navbar: "border-r border-surface-border bg-surface",
    navbarButton:
      "rounded-lg text-sm font-bold text-copy-secondary hover:bg-subtle hover:text-copy-primary data-[active=true]:bg-accent-dim data-[active=true]:text-brand",
    navbarButtonIcon: "text-current",
    navbarMobileMenuButton: "text-copy-primary",
    navbarMobileMenuRow: "bg-surface",
    scrollBox: "bg-surface",
    pageScrollBox: "bg-surface",
    page: "bg-surface",
    profileSection: "border-surface-border",
    profileSectionTitleText: "text-base font-extrabold text-copy-primary",
    profileSectionSubtitleText: "text-sm text-copy-secondary",
    profileSectionContent: "text-copy-primary",
    profileSectionPrimaryButton:
      "rounded-full border-[1.5px] border-surface-border bg-surface px-4 py-2 text-sm font-bold text-copy-primary hover:border-subtle-border hover:bg-subtle",
    accordionTriggerButton: "text-copy-primary hover:bg-subtle",
    accordionContent: "text-copy-secondary",
    avatarBox: "rounded-full",
    avatarImageActionsUpload: "text-brand hover:text-brand-hover",
    fileDropAreaBox: "rounded-xl border-surface-border bg-subtle",
    fileDropAreaButtonPrimary: "rounded-full bg-brand text-white hover:bg-brand-hover",
    fileDropAreaFooterHint: "text-copy-muted",
    menuButton: "text-copy-secondary hover:bg-subtle hover:text-copy-primary",
    menuList: "rounded-xl border border-surface-border bg-surface shadow-lg",
    menuItem: "text-copy-primary hover:bg-subtle",
    tableHead: "text-copy-muted",
    breadcrumbs: "text-copy-secondary",
    breadcrumbsItem: "text-copy-secondary",
    breadcrumbsItemDivider: "text-copy-faint",
    actionCard: "rounded-xl border-surface-border bg-subtle",
    badgeDanger: "rounded-full bg-error/10 text-error",
  },
} as const;
