import type { ItemKind, ItemStatus, ListingStatus, PriceUnit } from "@/types/supabase";

/** All Spanish copy for the admin panel (layout + Listados section). */
export const adminContent = {
  meta: {
    title: "Panel de administración — MILOCATIVA",
  },
  nav: {
    label: "Secciones del panel",
    backToSite: "Volver al sitio",
    items: {
      inbox: "Inbox",
      listings: "Listados",
      rentals: "Alquileres",
    },
    comingSoon: "Próximamente",
  },
  listings: {
    title: "Listados",
    subtitle: "Creá, editá y publicá los ítems del catálogo.",
    newItem: "Nuevo ítem",
    empty: "Todavía no hay ítems cargados. Creá el primero con “Nuevo ítem”.",
    table: {
      title: "Título",
      category: "Categoría",
      kind: "Tipo",
      price: "Precio",
      itemStatus: "Estado",
      publication: "Publicación",
      featured: "Destacado",
      actions: "Acciones",
      edit: "Editar",
      noCategory: "Sin categoría",
      noPrice: "Sin precio",
      notPublished: "Sin publicación",
      publishLabel: (title: string) => `Publicar ${title}`,
      featuredLabel: (title: string) => `Destacar ${title}`,
    },
  },
  form: {
    createTitle: "Nuevo ítem",
    editTitle: "Editar ítem",
    createSubtitle: "Elegí el tipo de ítem y completá sus datos.",
    editSubtitle: "Actualizá los datos del ítem.",
    kindLegend: "Tipo de ítem",
    kindLockedNote: "El tipo no se puede cambiar después de crear el ítem.",
    commonLegend: "Datos generales",
    subtypeLegend: "Datos específicos",
    fields: {
      title: "Título",
      titlePlaceholder: "Ej.: Monoambiente Torre Añelo 3A",
      description: "Descripción",
      descriptionPlaceholder: "Describí el ítem para el catálogo…",
      basePrice: "Precio base",
      basePricePlaceholder: "0",
      priceUnit: "Unidad de precio",
      category: "Categoría",
      categoryPlaceholder: "Elegí una categoría",
      status: "Estado del ítem",
      area: "Superficie (m²)",
      bedrooms: "Dormitorios",
      address: "Dirección",
      addressPlaceholder: "Calle y número, Añelo",
      brand: "Marca",
      model: "Modelo",
      year: "Año",
      serviceType: "Tipo de servicio",
      serviceTypePlaceholder: "Ej.: Transporte de personal",
      duration: "Duración",
      durationPlaceholder: "Ej.: Jornada completa",
      spotNumber: "Número de cochera",
      spotNumberPlaceholder: "Ej.: S1-04",
    },
    optional: "Opcional",
    save: "Guardar",
    publish: "Publicar",
    saving: "Guardando…",
    cancel: "Cancelar",
    publishToggle: "Publicar en el catálogo",
    publishToggleHint: "Si está apagado, el ítem se guarda como borrador.",
    discardConfirm: "Hay cambios sin guardar. ¿Los descartás?",
    closeLabel: "Cerrar",
    errors: {
      titleRequired: "El título es obligatorio.",
      priceInvalid: "El precio debe ser un número válido.",
      yearInvalid: "El año debe ser un número entero.",
      areaInvalid: "La superficie debe ser un número válido.",
      bedroomsInvalid: "Los dormitorios deben ser un número entero.",
      kindInvalid: "Elegí un tipo de ítem válido.",
      saveFailed: "No pudimos guardar el ítem. Probá de nuevo.",
      notFound: "No encontramos el ítem.",
      forbidden: "No tenés permisos para hacer esto.",
    },
  },
  kindLabels: {
    estate: "Inmueble",
    machinery: "Maquinaria",
    service: "Servicio",
    parking_spot: "Cochera",
  } satisfies Record<ItemKind, string>,
  itemStatusLabels: {
    draft: "Borrador",
    available: "Disponible",
    rented: "Alquilado",
    archived: "Archivado",
  } satisfies Record<ItemStatus, string>,
  listingStatusLabels: {
    draft: "Borrador",
    published: "Publicado",
    archived: "Archivado",
  } satisfies Record<ListingStatus, string>,
  priceUnitLabels: {
    month: "Por mes",
    day: "Por día",
    hour: "Por hora",
    service: "Por servicio",
    unit: "Por unidad",
  } satisfies Record<PriceUnit, string>,
} as const;
